language: python
matrix:
    include:
        -python: "2.7"
        env: TOXENV=py27
        -python: "3.5"
        env: TOXENV=py35

sudo: false # Use container-based infrastructure

# command to install dependencies
install:
    pip install tox

# command to run tests
script:
    tox
